server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/user/**

        - id: course-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/course/**
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials
      discovery:
        locator:
          enabled: true
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway